import type { Metadata } from "next";
import { DM_Sans, Gabriela } from "next/font/google";
import "./globals.css";

const dm_sans = DM_Sans({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
});

const gabriela = Gabriela({
	subsets: ["latin"],
	weight: "400", // Gabriela hanya tersedia dalam weight 400
	variable: "--font-gabriela",
});

export const metadata: Metadata = {
	title: "Kalkulator Umroh",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={`${dm_sans.className} ${gabriela.variable} antialiased`}
			>
				{children}
			</body>
		</html>
	);
}
